# This code is for plotting the data generated by model simulation

library(tidyverse)
library(ggplot2)
library(ggpubr)
library(tidytable)
library(scales)
library(rlang)
theme_set(theme_classic(base_size=11, base_family =''))

#---------------------part 1 -----------
# plot the aggregate the variable under different equilibrium(s).

scenario_name = c('mortality', 'popgrowth','mortality_popgrowth')
policy_name = c('adjust_replacement', 'adjust_tax','pension_reform')

eqm_list = expand.grid (scenario_name, policy_name) %>%
  filter (!( Var1 %in% c('mortality', 'popgrowth') &
             Var2 %in% c('adjust_replacement', 'adjust_tax') )) %>%
  mutate(eqm_name = paste0(Var1,'+',Var2)) %>%
  select (eqm_name) %>%unlist(.) 
   

var_list = c('Housing Price','Interest Rate','Wage',
  'Ownership','House Stock','Construction','kl_ratio', 'Land Profit','Transfer')

get_a = function (eqm){
     filename = paste0('./',eqm, '_aggregate.txt')  
     read_table(filename, col_names = var_list) %>%
     mutate(eqm = eqm)
}

data_aggregate = map (eqm_list, ~get_a(.))%>%
  reduce(rbind)%>%
  rbind( get_a('initial')) %>%
  # calculate the difference with the initial equilibrium
  mutate (across(where(is.numeric),   ~(.-nth(.,n()))/nth(.,n())  ) )%>%
  slice(1:n()-1)
  
# function to plot the change of aggregate
get_plot_aggregate = function (var_name){

  data_aggregate %>%
    ggplot (mapping = aes (x = reorder(eqm, !! sym(var_name)) ,
                          y =!! sym(var_name), fill = eqm))+
    labs(y =str_c('Percent Change in ', var_name))+
    geom_col()+coord_flip()+
    theme(legend.position = "none")+
    theme(axis.title.y=element_blank())

 }

# plot the price change 
plot_var_price = var_list[var_list %in% c('Housing Price','Interest Rate','Wage')] 
  ggarrange (plotlist = map (plot_var_price, ~get_plot_aggregate(.) ) , ncol = 2, nrow = 2) %>%
  ggsave (file = 'aggregate_price.png', plot = .,
        dpi = 'retina', width = 12.0, height = 6.0)

# plot the change in aggregate variables
plot_var_other = var_list[var_list %in% 
                      c('House Stock','Construction','Land Profit','Transfer')] #%>%
  ggarrange (plotlist = map (plot_var_other, ~get_plot_aggregate(.) ) , ncol = 2, nrow = 2) %>%
  ggsave (file = 'aggregate_other.png', plot = .,
          dpi = 'retina', width = 12.0, height = 6.0)

#---------------part 2: the life cycle 
# plot the average lice cycle profile for different equilibrium. 

# prepare for the life cycle data
get_life = function (eqm){

  age = map(seq(21, 90, by = 5), ~rep(.,5))%>%unlist(.)
  
  paste0 ('./',eqm,sep = '_life.txt')%>%
  read_table(., col_names = 
               c ('Cons', 'Non-House','House','Ownership','Income')) %>%
  cbind ( age) %>%
  group_by (age)%>%
  summarize (across(everything(), ~mean(.))) %>%
  mutate (eqm = eqm)
}

data_life = map(eqm_list, ~get_life(.)) %>%
  reduce(rbind) %>%
  rbind (get_life('initial'))

plot_life_var = function (eqm_list, var_name){

 data_life%>%filter(eqm %in% eqm_list) %>%
    ggplot(mapping = aes(x= age,y = !!sym(var_name), color = eqm)) + 
    geom_line(size = 1)+
    labs(y = var_name,x='Age')+
    theme(legend.position = 'bottom')
    
}

plot_life = function (var_name){
  life_plot = map (eqm_list,~plot_average( c('initial',.), var_name) )#%>%
  filename = paste0('life_', var_name, '.png')
  ggarrange(plotlist = life_plot , ncol = 2, nrow =3) %>%
    ggsave (file = filename, plot = .,
            dpi = 'retina', width = 8.0, height = 8.0)
}

# now plot.
map(c ('Cons', 'Non-House','House','Ownership','Income'), ~plot_life(.))


# ----------part 3---------
# plot the change of housing wealth for each age and each productivty level. 

# get the data for grid point
gridh = read_table('gridh.txt') %>%
  rename (h_value = 1) %>%
  add_row(h_value = 0) %>%
  arrange (h_value) %>%
  mutate (h = row_number()) 

# For each (e, age), find out the average house
get_h_data = function(eqm){

  paste0 ('./',eqm,'_measure.txt') %>%
    read_table(.,col_names = c('e','h', 'b', 'j', 'm'))%>%
    filter(m>0)%>%
    left_join(gridh, by = 'h')%>%
    group_by (e,j)%>%
    summarize(average_h = h_value%*% m /sum (m))%>%
    mutate (age = 20 +floor((j-21)/5)*5  ) %>%
    ungroup()%>%
    group_by (e,age) %>%
    summarize (avg_h = mean(average_h))%>%
    ungroup()%>%
    rename_with(~paste(eqm, 'h',sep ='_' ), .cols = c(avg_h))

}


# get the house distribution from all the equilibrium(s)
df_house_split = map (eqm_list, ~get_h_data(.))%>%
  reduce(., function(a,b) inner_join(a,b,by = c('e','age'))) %>%
  inner_join (get_h_data('initial'), by = c('e','age'))

# each new equilibrium, we want to plot the the change of house distribution
plot_h_change = function (eqm){
  
  y.var = sym(paste0(eqm,'_h'))

  plot = df_house_split %>%
  #filter(age>=25)%>%
    ggplot(mapping = aes (x = age, 
    y = (!! y.var - initial_h)/initial_h  , fill = age))+
    geom_col()+ facet_wrap(~ e ,scales='free_x') +
    labs(y = 'perchange change ',x='Age')+
    theme(axis.line=element_line())+
    theme(strip.background =element_rect(fill="springgreen3"))+
    scale_y_continuous(labels = scales::percent)+
    theme(plot.title = element_text(hjust = 0.5))

  filename = paste ('hchange',eqm, sep = '_')%>%
    paste(., '.png', sep = '')
  ggsave (file = filename, plot = plot,
        dpi = 'retina', width = 9.6, height = 4.8)

}


# output the plot
map (eqm_list, ~plot_h_change(.))

